server:
  port: 8080
  servlet:
    context-path: /myweb

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/myweb"
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "lBLxSxAHrRMGv3NQ3yuE9GrCIKMGoEisjuRfnMIPcilOHQ/AO+ChF+jrKAZItejIjnJew735TKZkFFjyMQ/FSvR6XoBDL/XeusAAJBhPA2c="